import React, { useEffect } from 'react';
import { ArrowLeft, Scale } from 'lucide-react';
import { BrandWordmark } from './BrandWordmark';

interface Props { onVolver: () => void; }
const FECHA = '14 de septiembre de 2026';
const Seccion: React.FC<{ id: string; titulo: string; children: React.ReactNode }> = ({ id, titulo, children }) => <section id={id} className="scroll-mt-8 border-t border-[var(--fin-line)] py-9 first:border-t-0 first:pt-0"><h2 className="text-xl font-black tracking-tight text-[var(--fin-ink)] sm:text-2xl">{titulo}</h2><div className="mt-4 space-y-4 text-sm leading-7 text-[var(--fin-ink-soft)]">{children}</div></section>;
const Sub: React.FC<{ children: React.ReactNode }> = ({ children }) => <h3 className="pt-2 text-base font-bold text-[var(--fin-ink)]">{children}</h3>;

export const LegalLukApp: React.FC<Props> = ({ onVolver }) => {
  useEffect(() => { document.title = 'Términos, privacidad y datos | LukApp'; window.scrollTo({ top: 0, behavior: 'auto' }); }, []);
  return <main className="min-h-[100dvh] bg-[var(--fin-bg)] px-4 py-5 text-[var(--fin-ink)] sm:px-6 sm:py-8"><div className="mx-auto max-w-4xl">
    <header className="rounded-3xl border border-[var(--fin-line)] bg-[var(--fin-card)] p-6 shadow-sm sm:p-9"><div className="flex items-center justify-between gap-4"><button type="button" onClick={onVolver} className="inline-flex items-center gap-2 rounded-xl px-2 py-1.5 text-sm font-semibold text-[var(--fin-ink-soft)] hover:bg-[var(--fin-soft)]"><ArrowLeft size={17} aria-hidden /> Volver a LukApp</button><BrandWordmark className="h-7 w-auto" /></div><div className="mt-10 max-w-2xl"><span className="inline-flex items-center gap-2 rounded-full bg-[var(--fin-accent)]/10 px-3 py-1.5 text-xs font-bold text-[var(--fin-accent)]"><Scale size={14} aria-hidden /> Información legal</span><h1 className="mt-4 text-3xl font-black tracking-tight sm:text-5xl">Términos, privacidad y uso de datos</h1><p className="mt-4 text-base leading-7 text-[var(--fin-ink-soft)]">Las reglas claras para usar LukApp y entender qué información se guarda, cuándo se usa y cómo ejercer tus derechos.</p><p className="mt-5 text-xs font-semibold text-[var(--fin-ink-faint)]">Última actualización: {FECHA}</p></div></header>
    <aside className="mt-5 rounded-2xl border border-amber-400/40 bg-amber-500/10 p-5 text-sm leading-6 text-[var(--fin-ink-soft)]"><strong className="text-[var(--fin-ink)]">Dato pendiente antes de publicar.</strong><p className="mt-1">Ya identificamos al responsable y su canal de contacto. Falta incorporar la dirección de notificaciones judiciales o administrativas; no se incluye aquí porque no fue suministrada.</p></aside>
    <nav aria-label="Índice legal" className="sticky top-3 z-10 mt-5 flex gap-2 overflow-x-auto rounded-2xl border border-[var(--fin-line)] bg-[var(--fin-card)] p-2 text-xs font-bold shadow-sm">{[['terminos', 'Términos'], ['privacidad', 'Privacidad'], ['datos', 'Tus datos'], ['almacenamiento', 'Almacenamiento'], ['licencia', 'Licencia']].map(([id, texto]) => <a key={id} href={`#${id}`} className="whitespace-nowrap rounded-xl px-3 py-2 text-[var(--fin-ink-soft)] hover:bg-[var(--fin-soft)] hover:text-[var(--fin-ink)]">{texto}</a>)}</nav>
    <article className="mt-5 rounded-3xl border border-[var(--fin-line)] bg-[var(--fin-card)] p-6 shadow-sm sm:p-10">
      <Seccion id="terminos" titulo="1. Términos y condiciones de uso"><p>Estos términos regulan el acceso a LukApp, su sitio web, versión instalada como aplicación web progresiva y funciones asociadas. Al crear una cuenta, acceder o utilizar LukApp, aceptas este documento. Si no estás de acuerdo, no uses el servicio.</p><Sub>Qué ofrece LukApp</Sub><p>LukApp es una herramienta de organización de finanzas personales orientada a Colombia. Permite registrar movimientos, presupuestos, metas, obligaciones, gastos compartidos y proyecciones. Algunas funciones pueden usar voz, procesamiento automatizado o un asesor basado en inteligencia artificial.</p><p>LukApp no es un banco, entidad financiera, comisionista, aseguradora, operador de pagos, asesor financiero profesional ni central de riesgo. No custodia dinero, no ejecuta transferencias, no toma decisiones de crédito y no sustituye el análisis de una persona profesional autorizada.</p><Sub>Uso permitido y cuenta</Sub><p>Debes usar la aplicación de forma lícita, personal y responsable. La información que ingreses debe ser tuya o estar autorizada. Eres responsable de proteger tu contraseña y avisar si sospechas acceso no autorizado. No está permitido vulnerar el servicio, extraer datos de otras personas, eludir controles, usar automatizaciones abusivas ni introducir contenido ilícito.</p><Sub>Información financiera y decisiones</Sub><p>Los cálculos, clasificaciones, alertas, proyecciones y respuestas del Asesor son informativos. Pueden contener errores o depender de datos incompletos. Antes de invertir, endeudarte, contratar un producto o tomar una decisión relevante, verifica la información y consulta a un profesional cuando corresponda.</p><Sub>Disponibilidad y propiedad intelectual</Sub><p>Podemos actualizar, corregir, limitar o retirar funciones por seguridad, mantenimiento, requisitos legales o evolución del producto. La marca, diseños, código, textos y funcionalidades están protegidos por la ley. Te otorgamos una licencia limitada, personal, revocable, no exclusiva e intransferible para usar LukApp. Tus datos financieros siguen siendo tuyos.</p></Seccion>
      <Seccion id="privacidad" titulo="2. Política de tratamiento de datos personales"><p>LukApp trata datos personales conforme a la Ley 1581 de 2012, el Decreto 1074 de 2015 y las demás normas colombianas aplicables.</p><Sub>Responsable y datos tratados</Sub><p><strong>Responsable:</strong> Julián Santiago González Reina, identificado con cédula de ciudadanía No. 1.104.547.389. <strong>Canal de protección de datos:</strong> <a className="font-semibold text-[var(--fin-accent)] underline underline-offset-2" href="mailto:jsgonzalezdevs@gmail.com">jsgonzalezdevs@gmail.com</a>. Tratamos correo, identificador técnico de usuario y credenciales administradas por el proveedor de autenticación; además de los datos que decides registrar: movimientos, montos, fechas, categorías, presupuestos, metas, deudas, tarjetas, cuentas, notas, contactos, conversaciones y recuerdos del Asesor cuando los habilitas, y audio únicamente cuando eliges transcribirlo.</p><Sub>Finalidades</Sub><p>Usamos la información para crear y proteger tu cuenta; almacenar, sincronizar y mostrar tus datos; prestar las funciones que solicitas; atender soporte; prevenir fraude, abuso y fallas; cumplir obligaciones legales; y mejorar el servicio con la analítica que aceptes expresamente. No vendemos tus datos financieros ni los usamos para perfiles publicitarios. Evita introducir datos sensibles. Si registras datos de otra persona, declaras que cuentas con autorización o una base legítima.</p><Sub>Encargados, seguridad y conservación</Sub><p>LukApp utiliza Supabase para autenticación y almacenamiento en la nube. Cuando usas transcripción, el audio se envía al proveedor configurado; cuando usas el Asesor, la consulta puede procesarse mediante servicios de inteligencia artificial a través de la API de LukApp. Estos proveedores pueden procesar datos fuera de Colombia. Aplicamos HTTPS/TLS, autenticación y reglas de acceso. Conservamos los datos mientras tu cuenta esté activa o sean necesarios para la finalidad informada, salvo obligación legal de conservarlos más tiempo.</p></Seccion>
      <Seccion id="datos" titulo="3. Tus derechos y cómo ejercerlos"><p>Como titular puedes conocer, actualizar, rectificar y solicitar prueba de la autorización sobre tus datos; ser informado sobre su uso; presentar quejas ante la Superintendencia de Industria y Comercio; revocar la autorización cuando proceda; y solicitar la supresión cuando no exista un deber legal o contractual de conservarlos.</p><p>Envía tu solicitud al canal de protección de datos del responsable indicando tu nombre, medio de respuesta, descripción clara de la petición y soportes para acreditar tu identidad. Las consultas y reclamos se atenderán dentro de los plazos previstos por la normativa colombiana. También puedes eliminar registros y exportar la información disponible desde la aplicación.</p></Seccion>
      <Seccion id="almacenamiento" titulo="4. Almacenamiento local, cookies y analítica"><Sub>Datos financieros y preferencias</Sub><p>Sin cuenta, la información se guarda en el almacenamiento de tu navegador o dispositivo. Si borras esos datos, cambias de dispositivo o desinstalas la aplicación, podrías perderlos. Con cuenta, LukApp puede sincronizarlos en la nube. Usamos almacenamiento local para recordar preferencias operativas, configuraciones, correo recordado cuando lo autorizas y tu decisión sobre analítica.</p><Sub>Analítica con consentimiento</Sub><p>Solo si aceptas la analítica detallada, LukApp registra categorías amplias de navegador, sistema operativo, idioma, tamaño de pantalla y zona horaria, junto con ruta y parámetros UTM. No guarda dirección IP, user-agent completo, cookies de terceros, contenido de tus finanzas ni identificadores persistentes para esa finalidad. Puedes rechazarla desde el aviso inicial o borrar la preferencia del navegador.</p><Sub>Voz e inteligencia artificial</Sub><p>La voz se activa solo tras conceder permiso al micrófono. Puedes detener una grabación; el audio cancelado no se envía a transcribir. La transcripción y el Asesor son opcionales: no introduzcas información que no quieras procesar para recibir esa respuesta. El Asesor puede guardar conversaciones o recuerdos únicamente según la configuración elegida.</p></Seccion>
      <Seccion id="licencia" titulo="5. Licencia, responsabilidad y ley aplicable"><p>La aplicación se entrega tal como está disponible, con las garantías que la ley no permita excluir. En la máxima medida permitida, LukApp no responde por pérdidas derivadas de decisiones basadas exclusivamente en proyecciones, respuestas automáticas, datos incorrectos, indisponibilidad de proveedores externos, pérdida de datos locales o descuido de credenciales. Esta cláusula no limita derechos irrenunciables de consumidores.</p><p>Si surge una diferencia, procuraremos resolverla primero por el canal de soporte. Estos términos se rigen por las leyes de Colombia, sin perjuicio de las normas imperativas de protección al consumidor y de datos. Podemos actualizar esta página por cambios del servicio, proveedores o normativa; publicaremos la fecha y comunicaremos los cambios materiales de forma razonable.</p></Seccion>
    </article><footer className="py-7 text-xs text-[var(--fin-ink-faint)]">© 2026 LukApp. Información legal y condiciones de uso.</footer>
  </div></main>;
};
